default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: virtual_taste_travels_development

test:
  <<: *default
  database: virtual_taste_travels_test

production:
  <<: *default
  database: virtual_taste_travels_production
  username: virtual_taste_travels
  password: <%= ENV["VIRTUAL_TASTE_TRAVELS_DATABASE_PASSWORD"] %>
